ALTER TABLE `Classroom`
  MODIFY `status` ENUM('ACTIVE', 'AVAILABLE', 'INACTIVE', 'MAINTENANCE') NOT NULL DEFAULT 'ACTIVE';

UPDATE `Classroom`
SET `status` = 'AVAILABLE'
WHERE `status` = 'ACTIVE';

ALTER TABLE `Classroom`
  MODIFY `status` ENUM('AVAILABLE', 'INACTIVE', 'MAINTENANCE') NOT NULL DEFAULT 'AVAILABLE';
