ALTER TABLE `Classroom`
  MODIFY `status` ENUM('AVAILABLE', 'ACTIVE', 'INACTIVE', 'MAINTENANCE') NOT NULL DEFAULT 'AVAILABLE';

UPDATE `Classroom`
SET `status` = 'ACTIVE'
WHERE `status` = 'AVAILABLE';

ALTER TABLE `Classroom`
  MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'MAINTENANCE') NOT NULL DEFAULT 'ACTIVE';
