ALTER TABLE `User`
  ADD COLUMN `userCode` VARCHAR(50) NULL,
  ADD COLUMN `firstName` VARCHAR(100) NULL,
  ADD COLUMN `lastName` VARCHAR(100) NULL,
  ADD COLUMN `phone` VARCHAR(20) NULL,
  ADD UNIQUE INDEX `User_userCode_key`(`userCode`);

ALTER TABLE `Classroom`
  ADD COLUMN `code` VARCHAR(50) NULL,
  ADD COLUMN `description` TEXT NULL,
  ADD COLUMN `category` VARCHAR(100) NULL,
  ADD UNIQUE INDEX `Classroom_code_key`(`code`);

ALTER TABLE `Notification`
  ADD COLUMN `readAt` DATETIME(3) NULL;

ALTER TABLE `User`
  MODIFY `status` ENUM('ACTIVE', 'INACTIVE', 'SUSPENDED') NOT NULL DEFAULT 'ACTIVE';

ALTER TABLE `Classroom`
  MODIFY `status` ENUM('AVAILABLE', 'INACTIVE', 'MAINTENANCE') NOT NULL DEFAULT 'AVAILABLE';
