const response = {
  Success: { type: 'object', properties: { success: { type: 'boolean', example: true }, message: { type: 'string', example: 'Success' }, data: { type: 'object' }, meta: { $ref: '#/components/schemas/Pagination' } } },
  Error: { type: 'object', required: ['success', 'message'], properties: { success: { type: 'boolean', example: false }, message: { type: 'string', example: 'Validation failed' }, errors: { type: 'array', items: { $ref: '#/components/schemas/FieldError' } } } }
};
const id = { name: 'id', in: 'path', required: true, schema: { type: 'integer', format: 'int64' } };
const bearer = [{ bearerAuth: [] }];
const extraPaths = {
  '/api/bookings/{id}': {
    get: { tags: ['Bookings'], summary: 'ดูรายละเอียดการจอง', security: bearer, parameters: [id], responses: { 200: { description: 'Booking detail' }, 404: { $ref: '#/components/responses/NotFound' } } },
    patch: { tags: ['Bookings'], summary: 'แก้ไขการจองสถานะ PENDING', security: bearer, parameters: [id], requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/Booking' } } } }, responses: { 200: { description: 'Booking updated' }, 409: { $ref: '#/components/responses/Conflict' } } },
    delete: { tags: ['Bookings'], summary: 'ยกเลิกการจองแบบ soft delete', security: bearer, parameters: [id], responses: { 200: { description: 'Booking cancelled' } } }
  },
  '/api/admin/classrooms/{id}': {
    get: { tags: ['Admin'], summary: 'รายละเอียดและประวัติห้อง', security: bearer, parameters: [id], responses: { 200: { description: 'Classroom detail' } } },
    patch: { tags: ['Admin'], summary: 'แก้ไขห้องเรียน', security: bearer, parameters: [id], requestBody: { content: { 'application/json': { schema: { $ref: '#/components/schemas/Classroom' } } } }, responses: { 200: { description: 'Classroom updated' } } },
    delete: { tags: ['Admin'], summary: 'ปิดใช้งานห้องแบบ soft delete', security: bearer, parameters: [id], responses: { 200: { description: 'Classroom deactivated' } } }
  },
  '/api/admin/bookings/{id}': { get: { tags: ['Admin'], summary: 'รายละเอียดและประวัติการจอง', security: bearer, parameters: [id], responses: { 200: { description: 'Booking detail with history' } } } },
  '/api/admin/bookings/{id}/cancel': { patch: { tags: ['Admin'], summary: 'Admin ยกเลิกการจอง', security: bearer, parameters: [id], requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['reason'], properties: { reason: { type: 'string' } } } } } }, responses: { 200: { description: 'Booking cancelled' } } } },
  '/api/admin/users/{id}': {
    get: { tags: ['Admin'], summary: 'ข้อมูลและประวัติผู้ใช้', security: bearer, parameters: [id], responses: { 200: { description: 'User detail' } } },
    patch: { tags: ['Admin'], summary: 'แก้ไขผู้ใช้', security: bearer, parameters: [id], responses: { 200: { description: 'User updated' } } },
    delete: { tags: ['Admin'], summary: 'ปิดผู้ใช้แบบ soft delete', security: bearer, parameters: [id], responses: { 200: { description: 'User deactivated' } } }
  },
  '/api/admin/users/{id}/role': { patch: { tags: ['Admin'], summary: 'เปลี่ยน Role', security: bearer, parameters: [id], responses: { 200: { description: 'Role updated' } } } },
  '/api/admin/users/{id}/reset-password': { patch: { tags: ['Admin'], summary: 'รีเซ็ตรหัสผ่าน', security: bearer, parameters: [id], responses: { 200: { description: 'Password reset' } } } },
  '/api/admin/reports/bookings': { get: { tags: ['Admin'], summary: 'รายงานการจอง', security: bearer, responses: { 200: { description: 'Booking report' } } } },
  '/api/admin/reports/classrooms': { get: { tags: ['Admin'], summary: 'สถิติการใช้ห้อง', security: bearer, responses: { 200: { description: 'Classroom report' } } } },
  '/api/admin/reports/users': { get: { tags: ['Admin'], summary: 'สถิติผู้ใช้', security: bearer, responses: { 200: { description: 'User report' } } } },
  '/api/admin/reports/export': { get: { tags: ['Admin'], summary: 'Export CSV', security: bearer, responses: { 200: { description: 'CSV file', content: { 'text/csv': { schema: { type: 'string' } } } } } } },
  '/api/admin/uploads/images': { post: { tags: ['Admin'], summary: 'อัปโหลดรูปภาพ สูงสุด 5 MB', security: bearer, requestBody: { required: true, content: { 'multipart/form-data': { schema: { type: 'object', required: ['image'], properties: { image: { type: 'string', format: 'binary' } } } } } }, responses: { 201: { description: 'Image uploaded' }, 400: { $ref: '#/components/responses/BadRequest' } } } },
  '/api/admin/uploads/images/{key}': { delete: { tags: ['Admin'], summary: 'ลบรูปภาพ local', security: bearer, parameters: [{ name: 'key', in: 'path', required: true, schema: { type: 'string' } }], responses: { 200: { description: 'Image deleted' } } } }
};
export const swaggerDocument = {
  openapi: '3.0.3',
  info: { title: 'Classroom Reservation API', version: '1.0.0', description: 'REST API สำหรับระบบจองห้องเรียน' },
  servers: [{ url: 'http://localhost:3000', description: 'Local server' }],
  tags: [{ name: 'Health' }, { name: 'Auth' }, { name: 'Users' }, { name: 'Classrooms' }, { name: 'Bookings' }, { name: 'Notifications' }, { name: 'Admin' }],
  components: {
    securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' } },
    schemas: {
      Success: response.Success,
      Pagination: { type: 'object', properties: { page: { type: 'integer', example: 1 }, limit: { type: 'integer', example: 20 }, total: { type: 'integer', example: 100 } } },
      FieldError: { type: 'object', properties: { field: { type: 'string', example: 'email' }, message: { type: 'string', example: 'Invalid email' } } },
      User: { type: 'object', properties: { id: { type: 'integer', format: 'int64' }, name: { type: 'string', example: 'Demo User' }, email: { type: 'string', format: 'email' }, role: { type: 'string', enum: ['USER', 'STUDENT', 'TEACHER', 'ADMIN'] }, status: { type: 'string', enum: ['ACTIVE', 'INACTIVE'] }, createdAt: { type: 'string', format: 'date-time' } } },
      Classroom: { type: 'object', properties: { id: { type: 'integer', format: 'int64' }, name: { type: 'string', example: 'A101' }, building: { type: 'string', example: 'Building A' }, floor: { type: 'string', example: '1' }, capacity: { type: 'integer', example: 40 }, equipment: { type: 'array', items: { type: 'string' } }, imageUrl: { type: 'string', format: 'uri', nullable: true }, status: { type: 'string', enum: ['AVAILABLE', 'INACTIVE'] } } },
      Booking: { type: 'object', properties: { id: { type: 'integer', format: 'int64' }, bookingCode: { type: 'string', example: 'BK-1720000000000-123' }, userId: { type: 'integer' }, classroomId: { type: 'integer' }, purpose: { type: 'string' }, description: { type: 'string' }, startAt: { type: 'string', format: 'date-time' }, endAt: { type: 'string', format: 'date-time' }, status: { type: 'string', enum: ['PENDING', 'CONFIRMED', 'REJECTED', 'CANCELLED', 'COMPLETED'] }, adminNote: { type: 'string' } } },
      Notification: { type: 'object', properties: { id: { type: 'integer' }, userId: { type: 'integer' }, title: { type: 'string' }, message: { type: 'string' }, type: { type: 'string' }, isRead: { type: 'boolean' }, createdAt: { type: 'string', format: 'date-time' } } }
    },
    responses: { BadRequest: { description: 'ข้อมูลไม่ถูกต้อง', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } }, Unauthorized: { description: 'ยังไม่ได้ Login หรือ Token ไม่ถูกต้อง', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } }, Forbidden: { description: 'ไม่มีสิทธิ์', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } }, NotFound: { description: 'ไม่พบข้อมูล', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } }, Conflict: { description: 'ข้อมูลซ้ำหรือเวลาจองชนกัน', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } } }
  },
  paths: {
    '/health': { get: { tags: ['Health'], summary: 'ตรวจสอบสถานะ API', responses: { 200: { description: 'Healthy', content: { 'application/json': { schema: { $ref: '#/components/schemas/Success' } } } } } } },
    '/api/auth/register': { post: { tags: ['Auth'], summary: 'สมัครสมาชิก', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['name', 'email', 'password'], properties: { name: { type: 'string', example: 'Demo User' }, email: { type: 'string', format: 'email' }, password: { type: 'string', format: 'password', minLength: 8 } } } } } }, responses: { 201: { description: 'สร้างผู้ใช้สำเร็จ' }, 400: { $ref: '#/components/responses/BadRequest' }, 409: { $ref: '#/components/responses/Conflict' } } } },
    '/api/auth/login': { post: { tags: ['Auth'], summary: 'เข้าสู่ระบบและรับ JWT', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['email', 'password'], properties: { email: { type: 'string', format: 'email' }, password: { type: 'string', format: 'password' } } } } } }, responses: { 200: { description: 'เข้าสู่ระบบสำเร็จ' }, 401: { $ref: '#/components/responses/Unauthorized' } } } },
    '/api/auth/me': { get: { tags: ['Auth'], summary: 'ดูผู้ใช้ที่ login อยู่', security: bearer, responses: { 200: { description: 'ข้อมูลผู้ใช้', content: { 'application/json': { schema: { $ref: '#/components/schemas/Success' } } } }, 401: { $ref: '#/components/responses/Unauthorized' } } } },
    '/api/users/me': { get: { tags: ['Users'], summary: 'ดูโปรไฟล์ตัวเอง', security: bearer, responses: { 200: { description: 'โปรไฟล์ผู้ใช้' }, 401: { $ref: '#/components/responses/Unauthorized' } } }, patch: { tags: ['Users'], summary: 'แก้ไขโปรไฟล์', security: bearer, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', properties: { name: { type: 'string' }, email: { type: 'string', format: 'email' } } } } } }, responses: { 200: { description: 'แก้ไขสำเร็จ' }, 400: { $ref: '#/components/responses/BadRequest' } } } },
    '/api/users/me/password': { patch: { tags: ['Users'], summary: 'เปลี่ยนรหัสผ่าน', security: bearer, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['currentPassword', 'newPassword'], properties: { currentPassword: { type: 'string', format: 'password' }, newPassword: { type: 'string', format: 'password', minLength: 8 } } } } } }, responses: { 200: { description: 'เปลี่ยนสำเร็จ' }, 400: { $ref: '#/components/responses/BadRequest' } } } },
    '/api/classrooms': { get: { tags: ['Classrooms'], summary: 'ค้นหาห้องเรียนที่เปิดใช้งาน', security: bearer, parameters: [{ name: 'search', in: 'query', schema: { type: 'string' } }, { name: 'building', in: 'query', schema: { type: 'string' } }, { name: 'minCapacity', in: 'query', schema: { type: 'integer' } }, { name: 'page', in: 'query', schema: { type: 'integer', default: 1 } }, { name: 'limit', in: 'query', schema: { type: 'integer', default: 20, maximum: 100 } }], responses: { 200: { description: 'รายการห้องเรียน' } } } },
    '/api/classrooms/{id}': { get: { tags: ['Classrooms'], summary: 'ดูรายละเอียดห้องเรียน', security: bearer, parameters: [id], responses: { 200: { description: 'ข้อมูลห้องเรียน' }, 404: { $ref: '#/components/responses/NotFound' } } } },
    '/api/classrooms/{id}/availability': { get: { tags: ['Classrooms'], summary: 'ตรวจสอบห้องว่าง', security: bearer, parameters: [id, { name: 'startAt', in: 'query', required: true, schema: { type: 'string', format: 'date-time' } }, { name: 'endAt', in: 'query', required: true, schema: { type: 'string', format: 'date-time' } }], responses: { 200: { description: 'ผลการตรวจสอบ' }, 400: { $ref: '#/components/responses/BadRequest' } } } },
    '/api/bookings': { get: { tags: ['Bookings'], summary: 'ดูรายการจองของตัวเอง', security: bearer, parameters: [{ name: 'status', in: 'query', schema: { type: 'string', enum: ['PENDING', 'CONFIRMED', 'REJECTED', 'CANCELLED', 'COMPLETED'] } }, { name: 'page', in: 'query', schema: { type: 'integer', default: 1 } }, { name: 'limit', in: 'query', schema: { type: 'integer', default: 20 } }], responses: { 200: { description: 'รายการจอง' } } }, post: { tags: ['Bookings'], summary: 'สร้างรายการจอง', security: bearer, requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['classroomId', 'purpose', 'startAt', 'endAt'], properties: { classroomId: { type: 'integer' }, purpose: { type: 'string' }, description: { type: 'string' }, startAt: { type: 'string', format: 'date-time' }, endAt: { type: 'string', format: 'date-time' } } } } } }, responses: { 201: { description: 'สร้างรายการจองสำเร็จ' }, 400: { $ref: '#/components/responses/BadRequest' }, 409: { $ref: '#/components/responses/Conflict' } } } },
    '/api/users/me/bookings': { get: { tags: ['Bookings'], summary: 'ประวัติการจองของตัวเอง', security: bearer, responses: { 200: { description: 'ประวัติการจอง' } } } },
    '/api/bookings/{id}/cancel': { patch: { tags: ['Bookings'], summary: 'ยกเลิกรายการจอง', security: bearer, parameters: [id], responses: { 200: { description: 'ยกเลิกสำเร็จ' }, 400: { $ref: '#/components/responses/BadRequest' }, 404: { $ref: '#/components/responses/NotFound' } } } },
    '/api/notifications': { get: { tags: ['Notifications'], summary: 'ดู notifications ของตัวเอง', security: bearer, responses: { 200: { description: 'รายการ notifications' } } } },
    '/api/notifications/read-all': { patch: { tags: ['Notifications'], summary: 'อ่าน notifications ทั้งหมด', security: bearer, responses: { 200: { description: 'สำเร็จ' } } } },
    '/api/notifications/{id}/read': { patch: { tags: ['Notifications'], summary: 'อ่าน notification', security: bearer, parameters: [id], responses: { 200: { description: 'สำเร็จ' }, 404: { $ref: '#/components/responses/NotFound' } } } },
    '/api/admin/dashboard/summary': { get: { tags: ['Admin'], summary: 'Dashboard summary', security: bearer, responses: { 200: { description: 'สรุป dashboard' }, 403: { $ref: '#/components/responses/Forbidden' } } } },
    '/api/admin/dashboard/recent-bookings': { get: { tags: ['Admin'], summary: 'รายการจองล่าสุด', security: bearer, parameters: [{ name: 'limit', in: 'query', schema: { type: 'integer', default: 10, maximum: 100 } }], responses: { 200: { description: 'รายการจองล่าสุด' } } } },
    '/api/admin/classrooms': { get: { tags: ['Admin'], summary: 'ดูห้องเรียนทั้งหมด', security: bearer, responses: { 200: { description: 'รายการห้องเรียน' } } }, post: { tags: ['Admin'], summary: 'สร้างห้องเรียน', security: bearer, requestBody: { required: true, content: { 'application/json': { schema: { $ref: '#/components/schemas/Classroom' } } } }, responses: { 201: { description: 'สร้างสำเร็จ' }, 403: { $ref: '#/components/responses/Forbidden' } } } },
    '/api/admin/classrooms/{id}/status': { patch: { tags: ['Admin'], summary: 'เปลี่ยนสถานะห้องเรียน', security: bearer, parameters: [id], requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['status'], properties: { status: { type: 'string', enum: ['AVAILABLE', 'INACTIVE'] } } } } } }, responses: { 200: { description: 'แก้ไขสำเร็จ' }, 403: { $ref: '#/components/responses/Forbidden' } } } },
    '/api/admin/bookings': { get: { tags: ['Admin'], summary: 'ดูรายการจองทั้งหมด', security: bearer, responses: { 200: { description: 'รายการจองทั้งหมด' }, 403: { $ref: '#/components/responses/Forbidden' } } } },
    '/api/admin/bookings/{id}/approve': { patch: { tags: ['Admin'], summary: 'อนุมัติการจอง', security: bearer, parameters: [id], responses: { 200: { description: 'อนุมัติสำเร็จ' }, 409: { $ref: '#/components/responses/Conflict' } } } },
    '/api/admin/bookings/{id}/reject': { patch: { tags: ['Admin'], summary: 'ปฏิเสธการจอง', security: bearer, parameters: [id], requestBody: { content: { 'application/json': { schema: { type: 'object', properties: { adminNote: { type: 'string' } } } } } }, responses: { 200: { description: 'ปฏิเสธสำเร็จ' } } } },
    '/api/admin/users': { get: { tags: ['Admin'], summary: 'ดูผู้ใช้งานทั้งหมด', security: bearer, responses: { 200: { description: 'รายการผู้ใช้งาน' } } } },
    '/api/admin/users/{id}/status': { patch: { tags: ['Admin'], summary: 'เปลี่ยนสถานะผู้ใช้', security: bearer, parameters: [id], requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['status'], properties: { status: { type: 'string', enum: ['ACTIVE', 'INACTIVE'] } } } } } }, responses: { 200: { description: 'แก้ไขสำเร็จ' } } } },
    '/api/admin/reports/summary': { get: { tags: ['Admin'], summary: 'รายงานสรุป', security: bearer, responses: { 200: { description: 'รายงานสรุป' } } } },
    '/api/admin/audit-logs': { get: { tags: ['Admin'], summary: 'ดู audit logs', security: bearer, responses: { 200: { description: 'รายการ audit logs' } } } },
    ...extraPaths
  }
};
